/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AvvikelserRouteImport } from './routes/avvikelser'
import { Route as BevakningarRouteImport } from './routes/bevakningar'
import { Route as ImporteraRouteImport } from './routes/importera'
import { Route as JamforRouteImport } from './routes/jamfor'
import { Route as KallorOchMetodRouteImport } from './routes/kallor-och-metod'
import { Route as NeutralitetRouteImport } from './routes/neutralitet'
import { Route as OmInsiktRouteImport } from './routes/om-insikt'
import { Route as OrdlistaRouteImport } from './routes/ordlista'
import { Route as RapporteraFelRouteImport } from './routes/rapportera-fel'
import { Route as SokRouteImport } from './routes/sok'
import { Route as SplittringarRouteImport } from './routes/splittringar'
import { Route as ValloftenRouteImport } from './routes/valloften'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ArendenIdRouteImport } from './routes/arenden/$id'
import { Route as LedamoterIndexRouteImport } from './routes/ledamoter/index'
import { Route as LedamoterIdRouteImport } from './routes/ledamoter/$id'
import { Route as PartierIndexRouteImport } from './routes/partier/index'
import { Route as PartierKodRouteImport } from './routes/partier/$kod'
import { Route as SakfragorIndexRouteImport } from './routes/sakfragor/index'
import { Route as SakfragorSlugRouteImport } from './routes/sakfragor/$slug'
import { Route as ValkretsarIndexRouteImport } from './routes/valkretsar/index'
import { Route as ValkretsarNamnRouteImport } from './routes/valkretsar/$namn'
import { Route as VoteringarIndexRouteImport } from './routes/voteringar/index'
import { Route as VoteringarIdRouteImport } from './routes/voteringar/$id'
import { Route as ApiPublicHooksInlasningRouteImport } from './routes/api/public/hooks/inlasning'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AvvikelserRoute = AvvikelserRouteImport.update({
  id: '/avvikelser',
  path: '/avvikelser',
  getParentRoute: () => rootRouteImport,
} as any)
const BevakningarRoute = BevakningarRouteImport.update({
  id: '/bevakningar',
  path: '/bevakningar',
  getParentRoute: () => rootRouteImport,
} as any)
const ImporteraRoute = ImporteraRouteImport.update({
  id: '/importera',
  path: '/importera',
  getParentRoute: () => rootRouteImport,
} as any)
const JamforRoute = JamforRouteImport.update({
  id: '/jamfor',
  path: '/jamfor',
  getParentRoute: () => rootRouteImport,
} as any)
const KallorOchMetodRoute = KallorOchMetodRouteImport.update({
  id: '/kallor-och-metod',
  path: '/kallor-och-metod',
  getParentRoute: () => rootRouteImport,
} as any)
const NeutralitetRoute = NeutralitetRouteImport.update({
  id: '/neutralitet',
  path: '/neutralitet',
  getParentRoute: () => rootRouteImport,
} as any)
const OmInsiktRoute = OmInsiktRouteImport.update({
  id: '/om-insikt',
  path: '/om-insikt',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdlistaRoute = OrdlistaRouteImport.update({
  id: '/ordlista',
  path: '/ordlista',
  getParentRoute: () => rootRouteImport,
} as any)
const RapporteraFelRoute = RapporteraFelRouteImport.update({
  id: '/rapportera-fel',
  path: '/rapportera-fel',
  getParentRoute: () => rootRouteImport,
} as any)
const SokRoute = SokRouteImport.update({
  id: '/sok',
  path: '/sok',
  getParentRoute: () => rootRouteImport,
} as any)
const SplittringarRoute = SplittringarRouteImport.update({
  id: '/splittringar',
  path: '/splittringar',
  getParentRoute: () => rootRouteImport,
} as any)
const ValloftenRoute = ValloftenRouteImport.update({
  id: '/valloften',
  path: '/valloften',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ArendenIdRoute = ArendenIdRouteImport.update({
  id: '/arenden/$id',
  path: '/arenden/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LedamoterIndexRoute = LedamoterIndexRouteImport.update({
  id: '/ledamoter/',
  path: '/ledamoter/',
  getParentRoute: () => rootRouteImport,
} as any)
const LedamoterIdRoute = LedamoterIdRouteImport.update({
  id: '/ledamoter/$id',
  path: '/ledamoter/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PartierIndexRoute = PartierIndexRouteImport.update({
  id: '/partier/',
  path: '/partier/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartierKodRoute = PartierKodRouteImport.update({
  id: '/partier/$kod',
  path: '/partier/$kod',
  getParentRoute: () => rootRouteImport,
} as any)
const SakfragorIndexRoute = SakfragorIndexRouteImport.update({
  id: '/sakfragor/',
  path: '/sakfragor/',
  getParentRoute: () => rootRouteImport,
} as any)
const SakfragorSlugRoute = SakfragorSlugRouteImport.update({
  id: '/sakfragor/$slug',
  path: '/sakfragor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ValkretsarIndexRoute = ValkretsarIndexRouteImport.update({
  id: '/valkretsar/',
  path: '/valkretsar/',
  getParentRoute: () => rootRouteImport,
} as any)
const ValkretsarNamnRoute = ValkretsarNamnRouteImport.update({
  id: '/valkretsar/$namn',
  path: '/valkretsar/$namn',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteringarIndexRoute = VoteringarIndexRouteImport.update({
  id: '/voteringar/',
  path: '/voteringar/',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteringarIdRoute = VoteringarIdRouteImport.update({
  id: '/voteringar/$id',
  path: '/voteringar/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksInlasningRoute = ApiPublicHooksInlasningRouteImport.update({
  id: '/api/public/hooks/inlasning',
  path: '/api/public/hooks/inlasning',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/avvikelser': typeof AvvikelserRoute
  '/bevakningar': typeof BevakningarRoute
  '/importera': typeof ImporteraRoute
  '/jamfor': typeof JamforRoute
  '/kallor-och-metod': typeof KallorOchMetodRoute
  '/neutralitet': typeof NeutralitetRoute
  '/om-insikt': typeof OmInsiktRoute
  '/ordlista': typeof OrdlistaRoute
  '/rapportera-fel': typeof RapporteraFelRoute
  '/sok': typeof SokRoute
  '/splittringar': typeof SplittringarRoute
  '/valloften': typeof ValloftenRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/arenden/$id': typeof ArendenIdRoute
  '/ledamoter/$id': typeof LedamoterIdRoute
  '/partier/$kod': typeof PartierKodRoute
  '/sakfragor/$slug': typeof SakfragorSlugRoute
  '/valkretsar/$namn': typeof ValkretsarNamnRoute
  '/voteringar/$id': typeof VoteringarIdRoute
  '/ledamoter/': typeof LedamoterIndexRoute
  '/partier/': typeof PartierIndexRoute
  '/sakfragor/': typeof SakfragorIndexRoute
  '/valkretsar/': typeof ValkretsarIndexRoute
  '/voteringar/': typeof VoteringarIndexRoute
  '/api/public/hooks/inlasning': typeof ApiPublicHooksInlasningRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/avvikelser': typeof AvvikelserRoute
  '/bevakningar': typeof BevakningarRoute
  '/importera': typeof ImporteraRoute
  '/jamfor': typeof JamforRoute
  '/kallor-och-metod': typeof KallorOchMetodRoute
  '/neutralitet': typeof NeutralitetRoute
  '/om-insikt': typeof OmInsiktRoute
  '/ordlista': typeof OrdlistaRoute
  '/rapportera-fel': typeof RapporteraFelRoute
  '/sok': typeof SokRoute
  '/splittringar': typeof SplittringarRoute
  '/valloften': typeof ValloftenRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/arenden/$id': typeof ArendenIdRoute
  '/ledamoter/$id': typeof LedamoterIdRoute
  '/partier/$kod': typeof PartierKodRoute
  '/sakfragor/$slug': typeof SakfragorSlugRoute
  '/valkretsar/$namn': typeof ValkretsarNamnRoute
  '/voteringar/$id': typeof VoteringarIdRoute
  '/ledamoter': typeof LedamoterIndexRoute
  '/partier': typeof PartierIndexRoute
  '/sakfragor': typeof SakfragorIndexRoute
  '/valkretsar': typeof ValkretsarIndexRoute
  '/voteringar': typeof VoteringarIndexRoute
  '/api/public/hooks/inlasning': typeof ApiPublicHooksInlasningRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/avvikelser': typeof AvvikelserRoute
  '/bevakningar': typeof BevakningarRoute
  '/importera': typeof ImporteraRoute
  '/jamfor': typeof JamforRoute
  '/kallor-och-metod': typeof KallorOchMetodRoute
  '/neutralitet': typeof NeutralitetRoute
  '/om-insikt': typeof OmInsiktRoute
  '/ordlista': typeof OrdlistaRoute
  '/rapportera-fel': typeof RapporteraFelRoute
  '/sok': typeof SokRoute
  '/splittringar': typeof SplittringarRoute
  '/valloften': typeof ValloftenRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/arenden/$id': typeof ArendenIdRoute
  '/ledamoter/$id': typeof LedamoterIdRoute
  '/partier/$kod': typeof PartierKodRoute
  '/sakfragor/$slug': typeof SakfragorSlugRoute
  '/valkretsar/$namn': typeof ValkretsarNamnRoute
  '/voteringar/$id': typeof VoteringarIdRoute
  '/ledamoter/': typeof LedamoterIndexRoute
  '/partier/': typeof PartierIndexRoute
  '/sakfragor/': typeof SakfragorIndexRoute
  '/valkretsar/': typeof ValkretsarIndexRoute
  '/voteringar/': typeof VoteringarIndexRoute
  '/api/public/hooks/inlasning': typeof ApiPublicHooksInlasningRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/avvikelser'
    | '/bevakningar'
    | '/importera'
    | '/jamfor'
    | '/kallor-och-metod'
    | '/neutralitet'
    | '/om-insikt'
    | '/ordlista'
    | '/rapportera-fel'
    | '/sok'
    | '/splittringar'
    | '/valloften'
    | '/admin'
    | '/arenden/$id'
    | '/ledamoter/$id'
    | '/partier/$kod'
    | '/sakfragor/$slug'
    | '/valkretsar/$namn'
    | '/voteringar/$id'
    | '/ledamoter/'
    | '/partier/'
    | '/sakfragor/'
    | '/valkretsar/'
    | '/voteringar/'
    | '/api/public/hooks/inlasning'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/avvikelser'
    | '/bevakningar'
    | '/importera'
    | '/jamfor'
    | '/kallor-och-metod'
    | '/neutralitet'
    | '/om-insikt'
    | '/ordlista'
    | '/rapportera-fel'
    | '/sok'
    | '/splittringar'
    | '/valloften'
    | '/admin'
    | '/arenden/$id'
    | '/ledamoter/$id'
    | '/partier/$kod'
    | '/sakfragor/$slug'
    | '/valkretsar/$namn'
    | '/voteringar/$id'
    | '/ledamoter'
    | '/partier'
    | '/sakfragor'
    | '/valkretsar'
    | '/voteringar'
    | '/api/public/hooks/inlasning'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/avvikelser'
    | '/bevakningar'
    | '/importera'
    | '/jamfor'
    | '/kallor-och-metod'
    | '/neutralitet'
    | '/om-insikt'
    | '/ordlista'
    | '/rapportera-fel'
    | '/sok'
    | '/splittringar'
    | '/valloften'
    | '/_authenticated/admin'
    | '/arenden/$id'
    | '/ledamoter/$id'
    | '/partier/$kod'
    | '/sakfragor/$slug'
    | '/valkretsar/$namn'
    | '/voteringar/$id'
    | '/ledamoter/'
    | '/partier/'
    | '/sakfragor/'
    | '/valkretsar/'
    | '/voteringar/'
    | '/api/public/hooks/inlasning'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AvvikelserRoute: typeof AvvikelserRoute
  BevakningarRoute: typeof BevakningarRoute
  ImporteraRoute: typeof ImporteraRoute
  JamforRoute: typeof JamforRoute
  KallorOchMetodRoute: typeof KallorOchMetodRoute
  NeutralitetRoute: typeof NeutralitetRoute
  OmInsiktRoute: typeof OmInsiktRoute
  OrdlistaRoute: typeof OrdlistaRoute
  RapporteraFelRoute: typeof RapporteraFelRoute
  SokRoute: typeof SokRoute
  SplittringarRoute: typeof SplittringarRoute
  ValloftenRoute: typeof ValloftenRoute
  ArendenIdRoute: typeof ArendenIdRoute
  LedamoterIdRoute: typeof LedamoterIdRoute
  PartierKodRoute: typeof PartierKodRoute
  SakfragorSlugRoute: typeof SakfragorSlugRoute
  ValkretsarNamnRoute: typeof ValkretsarNamnRoute
  VoteringarIdRoute: typeof VoteringarIdRoute
  LedamoterIndexRoute: typeof LedamoterIndexRoute
  PartierIndexRoute: typeof PartierIndexRoute
  SakfragorIndexRoute: typeof SakfragorIndexRoute
  ValkretsarIndexRoute: typeof ValkretsarIndexRoute
  VoteringarIndexRoute: typeof VoteringarIndexRoute
  ApiPublicHooksInlasningRoute: typeof ApiPublicHooksInlasningRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avvikelser': {
      id: '/avvikelser'
      path: '/avvikelser'
      fullPath: '/avvikelser'
      preLoaderRoute: typeof AvvikelserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bevakningar': {
      id: '/bevakningar'
      path: '/bevakningar'
      fullPath: '/bevakningar'
      preLoaderRoute: typeof BevakningarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importera': {
      id: '/importera'
      path: '/importera'
      fullPath: '/importera'
      preLoaderRoute: typeof ImporteraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jamfor': {
      id: '/jamfor'
      path: '/jamfor'
      fullPath: '/jamfor'
      preLoaderRoute: typeof JamforRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kallor-och-metod': {
      id: '/kallor-och-metod'
      path: '/kallor-och-metod'
      fullPath: '/kallor-och-metod'
      preLoaderRoute: typeof KallorOchMetodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neutralitet': {
      id: '/neutralitet'
      path: '/neutralitet'
      fullPath: '/neutralitet'
      preLoaderRoute: typeof NeutralitetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-insikt': {
      id: '/om-insikt'
      path: '/om-insikt'
      fullPath: '/om-insikt'
      preLoaderRoute: typeof OmInsiktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordlista': {
      id: '/ordlista'
      path: '/ordlista'
      fullPath: '/ordlista'
      preLoaderRoute: typeof OrdlistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapportera-fel': {
      id: '/rapportera-fel'
      path: '/rapportera-fel'
      fullPath: '/rapportera-fel'
      preLoaderRoute: typeof RapporteraFelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sok': {
      id: '/sok'
      path: '/sok'
      fullPath: '/sok'
      preLoaderRoute: typeof SokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splittringar': {
      id: '/splittringar'
      path: '/splittringar'
      fullPath: '/splittringar'
      preLoaderRoute: typeof SplittringarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/valloften': {
      id: '/valloften'
      path: '/valloften'
      fullPath: '/valloften'
      preLoaderRoute: typeof ValloftenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/arenden/$id': {
      id: '/arenden/$id'
      path: '/arenden/$id'
      fullPath: '/arenden/$id'
      preLoaderRoute: typeof ArendenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledamoter/': {
      id: '/ledamoter/'
      path: '/ledamoter'
      fullPath: '/ledamoter/'
      preLoaderRoute: typeof LedamoterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledamoter/$id': {
      id: '/ledamoter/$id'
      path: '/ledamoter/$id'
      fullPath: '/ledamoter/$id'
      preLoaderRoute: typeof LedamoterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partier/': {
      id: '/partier/'
      path: '/partier'
      fullPath: '/partier/'
      preLoaderRoute: typeof PartierIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partier/$kod': {
      id: '/partier/$kod'
      path: '/partier/$kod'
      fullPath: '/partier/$kod'
      preLoaderRoute: typeof PartierKodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sakfragor/': {
      id: '/sakfragor/'
      path: '/sakfragor'
      fullPath: '/sakfragor/'
      preLoaderRoute: typeof SakfragorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sakfragor/$slug': {
      id: '/sakfragor/$slug'
      path: '/sakfragor/$slug'
      fullPath: '/sakfragor/$slug'
      preLoaderRoute: typeof SakfragorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/valkretsar/': {
      id: '/valkretsar/'
      path: '/valkretsar'
      fullPath: '/valkretsar/'
      preLoaderRoute: typeof ValkretsarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/valkretsar/$namn': {
      id: '/valkretsar/$namn'
      path: '/valkretsar/$namn'
      fullPath: '/valkretsar/$namn'
      preLoaderRoute: typeof ValkretsarNamnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voteringar/': {
      id: '/voteringar/'
      path: '/voteringar'
      fullPath: '/voteringar/'
      preLoaderRoute: typeof VoteringarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voteringar/$id': {
      id: '/voteringar/$id'
      path: '/voteringar/$id'
      fullPath: '/voteringar/$id'
      preLoaderRoute: typeof VoteringarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/inlasning': {
      id: '/api/public/hooks/inlasning'
      path: '/api/public/hooks/inlasning'
      fullPath: '/api/public/hooks/inlasning'
      preLoaderRoute: typeof ApiPublicHooksInlasningRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AvvikelserRoute: AvvikelserRoute,
  BevakningarRoute: BevakningarRoute,
  ImporteraRoute: ImporteraRoute,
  JamforRoute: JamforRoute,
  KallorOchMetodRoute: KallorOchMetodRoute,
  NeutralitetRoute: NeutralitetRoute,
  OmInsiktRoute: OmInsiktRoute,
  OrdlistaRoute: OrdlistaRoute,
  RapporteraFelRoute: RapporteraFelRoute,
  SokRoute: SokRoute,
  SplittringarRoute: SplittringarRoute,
  ValloftenRoute: ValloftenRoute,
  ArendenIdRoute: ArendenIdRoute,
  LedamoterIdRoute: LedamoterIdRoute,
  PartierKodRoute: PartierKodRoute,
  SakfragorSlugRoute: SakfragorSlugRoute,
  ValkretsarNamnRoute: ValkretsarNamnRoute,
  VoteringarIdRoute: VoteringarIdRoute,
  LedamoterIndexRoute: LedamoterIndexRoute,
  PartierIndexRoute: PartierIndexRoute,
  SakfragorIndexRoute: SakfragorIndexRoute,
  ValkretsarIndexRoute: ValkretsarIndexRoute,
  VoteringarIndexRoute: VoteringarIndexRoute,
  ApiPublicHooksInlasningRoute: ApiPublicHooksInlasningRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
